# Generated by Django 3.2.19 on 2023-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfridge',
            name='currentLat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userfridge',
            name='currentLong',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userfridge',
            name='locationStatus',
            field=models.BooleanField(default=False),
        ),
    ]
