# Generated by Django 3.2.19 on 2023-05-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_auto_20230515_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfridge',
            name='locationStatus',
        ),
    ]
