# Generated by Django 3.2.19 on 2023-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_remove_userfridge_locationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfridge',
            name='currentLat',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userfridge',
            name='currentLong',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userfridge',
            name='lat',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userfridge',
            name='long',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
