# Generated by Django 3.2.19 on 2023-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_auto_20230520_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
