# Generated by Django 3.2.19 on 2023-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_order_isapproved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreceive',
            old_name='userFridge',
            new_name='orderR',
        ),
        migrations.AddField(
            model_name='orderreceive',
            name='isGiven',
            field=models.BooleanField(default=False),
        ),
    ]
