# Generated by Django 3.2.19 on 2023-06-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uaa', '0003_auto_20230528_0407'),
        ('fridge', '0007_auto_20230602_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_order', to='uaa.branch'),
        ),
    ]
