# Generated by Django 3.2.19 on 2023-06-06 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_order_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deviceId', models.CharField(blank=True, max_length=25, null=True)),
                ('lat', models.CharField(blank=True, max_length=25, null=True)),
                ('long', models.CharField(blank=True, max_length=25, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userFridge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='usero',
        ),
        migrations.RemoveField(
            model_name='orderreceive',
            name='orderR',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='userfridge',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='userfridge',
            name='fridge',
        ),
        migrations.RemoveField(
            model_name='userfridge',
            name='updatedBy',
        ),
        migrations.RemoveField(
            model_name='userfridge',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderReceive',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='UserFridge',
        ),
    ]
